### ISSUE TITLE
修改mysql密码无效

### ISSUE THREAD

**Issue by sxd-mike** [huangmeng4520/palybook_mysql5.7#1]
你好，我修改了host之后，运行了原项目可以完美执行。
但我修改了mysql_user.sh的newpassword的值：
   newpassword=20181116

修改后，再用新环境执行，脚本执行成功，但是来到新机器里面登录mysql，密码为20181116则提示密码错误。请问修改该字段需要关联其他地方吗

**Comment by huangmeng4520** [comment]
mysql5.7对新密码的强度有要求的，你这密码太简单了。改个复杂的

**Comment by sxd-mike** [comment]
对，后面修改了密码强度就可以了。谢谢作者的解答
